const routes = {
  home: "/",
  about: "/about-invisiron/",
  products: "/invisiron-cyber-defence-systems/",
  sentryS1000: "/invisiron-cyber-defence-systems/invisiron-sentry-s-1000/",
  sentryS4000: "/invisiron-cyber-defence-systems/invisiron-sentry-s-4000/",
  sentryS6000: "/invisiron-cyber-defence-systems/invisiron-sentry-s-6000/",
  core: "/c3x-core-technology/",
  features: "/invisiron-key-features/",
  partner: "/partner/",
  blog: "/blog/",
  blogGrant: "/invisiron-pre-approved-digital-solution-grant/",
  cyberSecurityAsia: "/cyber-security-asia-2022/",
  cybersecurityTrends: "/5-cybersecurity-trends-in-2022/",
  cyberDefenceLegal: "/cyber-defence-its-time-to-act-now-cyber-security-and-the-pandemic-heightened-cyber-threats-in-the-legal-sector/",
  squirrelwaffle: "/breaking-news-new-malware-threat-squirrelwaffle-discovered/",
  thirdPartySoftware: "/third-party-software-bug-exploited-by-hackers/",
  surgeComplex: "/surge-in-complex-cyber-attacks-targeted-at-small-to-medium-enterprises/",
  upgradeCompany: "/upgrade-your-companys-cyber-security-networks-today/",
  aseanCyberattacks: "/7-most-prominent-cyberattacks-in-asean-countries/",
  cybersecurityTips: "/cybersecurity-tips-to-follow-when-working-from-home/",
  articles: "/category/articles/",
  events: "/category/events/",
  news: "/category/news/",
  cases: "/case-studies/",
  quebyCaseStudy: "/casestudy/a-malaysian-debt-recovery-operations-company-protected-from-pitou-ransomware/",
  onestopCaseStudy: "/casestudy/an-e-portal-platform-protected-from-cyber-threats-and-attacks/",
  asiaDefenceCaseStudy: "/casestudy/asias-largest-defence-engineering-group/",
  hostingThailandCaseStudy: "/casestudy/hosting-company-thailand/",
  logisticsCaseStudy: "/casestudy/logistics-industry/",
  maritimeCaseStudy: "/casestudy/maritime-industry/",
  seaGovernmentCaseStudy: "/casestudy/sea-government-agency/",
  technologyConsultancyCaseStudy: "/casestudy/technology-consultancy/",
  testimonials: "/testimonials/",
  contact: "/contact-invisiron/",
  privacy: "/privacy-and-gdpr-policy/",
} as const;

export { routes };
